[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && npx next start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
